$scriptName = $MyInvocation.MyCommand.Name

pdflatex .\example.tex

# You can get image magick using winget install ImageMagick.ImageMagick and then restarting your computer.
# Ensure that ghostscript is installed as well.
magick -density 75 .\example.pdf -quality 90 -background white -alpha remove -strip .\example.png

$readmefile = ".\README.md"

(
@"
# invoice.sty

## Prerequisites
You need to have [LaTeX installed](https://www.latex-project.org/get/).

## Usage
In a latex document, include the package ``invoice`` and then create invoices using the command
``````latex
\invoice{payee-address}{payer-address}{list of gigs}{bank details}
``````

## Useful subcommands
### ``\gig{Details}{Date}{Cost}``
An individual invoicable event. ``Cost`` should be a number only, no currency symbol.
``Details`` and ``Date`` are plain text fields.


### ``\bankdetailsuk{Account Name}{Sort Code}{Account Number}``
All fields are plain text.

## Example code
``````latex
% example.tex
"@
) | Set-Content -Path $readmefile

Get-Content .\example.tex |  Add-Content -Path $readmefile

(
@"
``````

You should be able to create the example file by running:
``````
pdflatex example.tex
``````
and you should end up with something that looks like this:

![the output](example.png)

## Next steps
- Allow decimals in costs
- Allow different currencies
- Allow tax calculations
- Allow different date formats
- Allow multiple pages in invoice table
- Allow for invoice dates other than the current day
- Allow for due dates other than one month from the current day


## Contact
Questions, suggestions and bug reports can be logged at https://github.com/ajasmith/invoices where you can also find the latest version.


_This file is auto-generated by ``$scriptName``. Do not edit it directly._
"@
) | Add-Content -Path $readmefile

Remove-Item *.aux
Remove-Item *.log
Remove-Item *.out
Remove-Item example.pdf